apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echo-server.fullname" . }}
  labels:
    {{- include "echo-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "echo-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "echo-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: {{ .Values.env.name }}
              value: {{ .Values.env.value }}
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: index-html
              mountPath: /app/index.html
              subPath: index.html
      volumes:
        - name: index-html
          configMap:
            name: index-html
