replicaCount: 1

image:
  repository: 329082085800.dkr.ecr.eu-central-1.amazonaws.com/echo-server
  tag: "9260709558"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

env:
  name: ENVIRONMENT
  value: "prod"  # Change this to "stage" or "int" as needed

indexHtmlContent: |
 <!DOCTYPE html>
  <html>
  <head>
      <title>Index Page</title>
  </head>
  <body>
      <h1>Welcome to the Echo Server</h1>
      <p>Echo Message: {{ECHO_MESSAGE}}</p>
      <p>Geo-location Data:</p>
      <pre>{{GEO_LOCATION}}</pre>
  </body>
  </html>

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
