replicaCount: 1

image:
  repository: 329082085800.dkr.ecr.eu-central-1.amazonaws.com/echo-server
  tag: "9276446401"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

env:
  name: ENVIRONMENT
  value: "prod"  # Change this to "stage" or "int" as needed

indexHtmlContent: |
  <!DOCTYPE html>
  <html>
    <head>
      <title>Geolocation and IP Example</title>
    </head>
  <body>

  <div id="geoLocation">Loading location...</div>
  <div id="ipAddress">Loading IP address...</div>

  <script>
  const geoLocationElement = document.getElementById("geoLocation");

  function getLocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(showPosition);
    } else {
      navigator.geolocation.getCurrentPosition(showPosition);
    
      geoLocationElement.innerHTML = "Geolocation is not supported by this browser.";
    }
  }

  function showPosition(position) {
    geoLocationElement.innerHTML = "Latitude: " + position.coords.latitude +
    "<br>Longitude: " + position.coords.longitude;
  }

  window.onload = getLocation;
  </script>

  <script type="application/javascript">
    function getIP(json) {
      document.getElementById("ipAddress").innerHTML = "My public IP address is: " + json.ip;
    }
  </script>

  <script type="application/javascript" src="https://ipinfo.io/?format=jsonp&callback=getIP"></script>

  </body>
  </html>

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
