name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        echo "FOO=$(git status)" >> $GITHUB_ENV
        echo "Tag=date +%s" >> $GITHUB_ENV
        echo "${{ env.FOO }}"
        echo "${{ env.Tag }}"
        docker build . --file Dockerfile --tag echo-server:"${{ env.Tag }}"
        docker run -d -p 8080:8080 -e ENVIRONMENT=staging echo-server:"${{ env.Tag }}"
        sleep 5
        curl localhost:8080 -vih
        #docker push <your-docker-registry>/echo-server:$(date +%s)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'
