name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      id: Tag
      with:
        run: date +'%Y-%m-%d'
    - run: |
        echo "${{ steps.Tag.outputs.stdout }}"
        docker build . --file Dockerfile --tag echo-server:"${{ steps.Tag.outputs.stdout }}"
        docker run -d -p 8080:8080 -e ENVIRONMENT=staging echo-server:"${{ steps.Tag.outputs.stdout }}"
        sleep 5
        curl localhost:8080 -vih
        #docker push <your-docker-registry>/echo-server:$(date +%s)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'
